"""A seeded synthetic daily corpus for the research positive control (Kevin's corpus lane).

## Why this exists

"Zero strategies selected" is claimed to be data-bound. Until something has been *selected*,
that claim and "the selection path cannot select" are the same observation, and only one of
them is comfortable. This module generates a corpus on which the real campaign pipeline
reaches a PASS, so the two become different observations.

## The shape, and why it is this shape

A returns schedule rather than a price formula, because the strategy consumes returns
implicitly through RSI(2) / EMA(20) / ATR(14) and a schedule is what makes the statistical
claim writable down:

- ``_DRIFT`` per bar on ordinary bars;
- every ``_PERIOD`` bars, **one** sharp down bar (``_DIP``) followed by a three-bar recovery;
- seeded uniform noise of ``+/- _NOISE`` so the series is not degenerate, and is still
  bit-reproducible from ``(seed, n_bars)``.

The dip is a *single* bar deliberately. RSI(2) after one -3% close that follows small gains
is far below the strategy's oversold level, so the entry fills at the bottom. Two earlier
shapes used a two-bar drawdown; RSI(2) crossed its threshold after the **first** bar, the
entry filled ahead of the second drop, and both shapes produced ample trades at a negative
Sharpe. The corpus has to be shaped against the strategy's exit rule and fill timing, not
only its entry condition — that is the whole lesson of the two failures.

## Not certified data, and structurally unable to be mistaken for it

The symbols are ``SYNTHA``/``SYNTHB``: not tickers, not plausible ones, and absent from
``config/risk.research.yaml``'s universe (asserted by the control). The manifest written
beside the CSVs carries ``synthetic: true`` and the shape below. Note that
``research.campaign.run_campaign`` reads **no manifest** — it opens ``<data_dir>/<SYMBOL>.csv``
and nothing else — so that flag is documentation for humans and a hook for the guard test,
never a pipeline input. A flag nothing reads is an unasserted claim; the control asserts it.
"""

from __future__ import annotations

import hashlib
import json
import random
from datetime import date, timedelta
from pathlib import Path

#: Names that cannot collide with a real instrument, and are not in the research universe.
SYNTHETIC_SYMBOLS = ("SYNTHA", "SYNTHB")

#: The documented statistical shape. Changing any of these changes the corpus, and the
#: control asserts the corpus digest, so a silent change fails as a data change.
_SEED = 20260905
_PERIOD = 21
_DIP = -0.030
_RECOVERY = (0.012, 0.010, 0.008)
_DRIFT = 0.0010
_NOISE = 0.0003
_START = date(2005, 1, 3)
_OPEN_PRICE = 100.0

SHAPE: dict[str, object] = {
    "model": "returns schedule: drift, one-bar dip, three-bar recovery, seeded uniform noise",
    "seed": _SEED,
    "period_bars": _PERIOD,
    "dip_return": _DIP,
    "recovery_returns": list(_RECOVERY),
    "drift_return_per_bar": _DRIFT,
    "noise_uniform_halfwidth": _NOISE,
    "first_session": _START.isoformat(),
    "sessions": "weekdays only",
    "open_convention": "each bar's open is the previous bar's close",
}


def _schedule(index: int) -> float:
    position = index % _PERIOD
    if position == 0:
        return _DIP
    if 1 <= position <= len(_RECOVERY):
        return _RECOVERY[position - 1]
    return _DRIFT


def write_synthetic_corpus(data_dir: Path, symbol: str, n_bars: int, *, seed: int = _SEED) -> Path:
    """Write ``<data_dir>/<symbol>.csv`` and return its path. Deterministic in (seed, n_bars)."""

    if symbol not in SYNTHETIC_SYMBOLS:
        raise ValueError(
            f"{symbol!r} is not a synthetic symbol; this generator writes only "
            f"{SYNTHETIC_SYMBOLS} so its output can never be mistaken for certified data"
        )
    rng = random.Random(seed)
    data_dir.mkdir(parents=True, exist_ok=True)
    lines = ["date,open,high,low,close,volume"]
    session = _START
    close = _OPEN_PRICE
    previous_close = _OPEN_PRICE
    for index in range(n_bars):
        while session.weekday() >= 5:
            session += timedelta(days=1)
        close = close * (1.0 + _schedule(index) + rng.uniform(-_NOISE, _NOISE))
        open_ = previous_close
        high = max(open_, close) * 1.0012
        low = min(open_, close) * 0.9988
        lines.append(f"{session.isoformat()},{open_:.4f},{high:.4f},{low:.4f},{close:.4f},1000000")
        previous_close = close
        session += timedelta(days=1)
    path = data_dir / f"{symbol}.csv"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def write_manifest(data_dir: Path, paths: dict[str, Path]) -> Path:
    """Write the SYNTHETIC manifest beside the corpus. Read by the control, not by the pipeline."""

    manifest = {
        "synthetic": True,
        "not_certified_data": (
            "generated by tests.support.synthetic_corpus for the research positive control; "
            "never a source of evidence about any real instrument"
        ),
        "generator": "tests.support.synthetic_corpus:write_synthetic_corpus",
        "shape": SHAPE,
        "files": {
            symbol: {
                "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
                "bars": len(path.read_text(encoding="utf-8").splitlines()) - 1,
            }
            for symbol, path in sorted(paths.items())
        },
    }
    path = data_dir / "MANIFEST.json"
    path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path


def corpus_digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()
