#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
REPO_ROOT=$(cd -- "$SCRIPT_DIR/.." && pwd -P)
PYTHON="$REPO_ROOT/.venv/bin/python"
PACKET_HELPER="$REPO_ROOT/scripts/prepare_qqq_certified_data.py"
CAMPAIGN_ROOT="${CHRONOS_QQQ_CAMPAIGN_ROOT:-$REPO_ROOT/research/data/campaigns/qqq-v1}"
HISTORY_ROOT="$CAMPAIGN_ROOT/history"
ACTION_INPUT_ROOT="$CAMPAIGN_ROOT/owner_actions"
CAPTURE_LOG="$CAMPAIGN_ROOT/capture.jsonl"
SOURCE_RECEIPT="$CAMPAIGN_ROOT/source_receipt.json"
DECLARATION="$CAMPAIGN_ROOT/certify.json"
RELEASE_ROOT="$CAMPAIGN_ROOT/releases/etf-daily-001"
ENV_FILE="$CAMPAIGN_ROOT/data.env"
SYMBOLS="QQQ,SPY,IWM,DIA,GLD,TLT"

mkdir -p "$CAMPAIGN_ROOT" "$HISTORY_ROOT" "$ACTION_INPUT_ROOT" "$(dirname "$RELEASE_ROOT")"
cd "$REPO_ROOT"

refuse() {
  warn "$1"
  exit 1
}

run_packet_python() {
  env \
    BROKER_MODE=demo \
    IB_ENVIRONMENT=paper \
    IB_HOST="$IB_HOST" \
    IB_PORT="$IB_PORT" \
    IB_CLIENT_ID="$IB_CLIENT_ID" \
    IB_DATA_CLIENT_ID="$IB_DATA_CLIENT_ID" \
    ALLOW_ORDER_TRANSMIT=false \
    ALLOW_LIVE_TRADING=false \
    "$PYTHON" "$@"
}

seed_default() {
  local key="$1" value="$2"
  [[ -n "$(_existing "$key" || true)" ]] || write_env "$key" "$value"
}

banner "Chronos · QQQ certified-data packet"

stage "Read-only gateway preflight"
say "This packet reads daily bars only. It cannot submit, modify, or cancel an order."
[[ -x "$PYTHON" ]] || refuse "missing $PYTHON; create the project virtual environment first"
[[ -f "$PACKET_HELPER" ]] || refuse "missing packet helper: $PACKET_HELPER"
seed_default IB_HOST "127.0.0.1"
seed_default IB_PORT "7497"
seed_default IB_CLIENT_ID "17"
seed_default IB_DATA_CLIENT_ID "18"
ask IB_HOST "IB Gateway/TWS host (recommended 127.0.0.1):"
ask IB_PORT "PAPER API port (recommended 7497):"
ask IB_CLIENT_ID "Trading-plane client id (recommended 17; used only for collision check):"
ask IB_DATA_CLIENT_ID "Dedicated read-only data client id (recommended 18):"
[[ "$IB_PORT" =~ ^[0-9]+$ ]] || refuse "IB_PORT must be numeric"
[[ "$IB_CLIENT_ID" =~ ^[0-9]+$ ]] || refuse "IB_CLIENT_ID must be numeric"
[[ "$IB_DATA_CLIENT_ID" =~ ^[0-9]+$ ]] || refuse "IB_DATA_CLIENT_ID must be numeric"
(( IB_DATA_CLIENT_ID >= 1 )) || refuse "IB_DATA_CLIENT_ID 0 is TWS master authority and is forbidden"
[[ "$IB_DATA_CLIENT_ID" != "$IB_CLIENT_ID" ]] || refuse "data and trading client ids must differ"
write_env IB_HOST "$IB_HOST"
write_env IB_PORT "$IB_PORT"
write_env IB_CLIENT_ID "$IB_CLIENT_ID"
write_env IB_DATA_CLIENT_ID "$IB_DATA_CLIENT_ID"
step "Start TWS or IB Gateway on the PAPER profile."
step "In API settings, check Read-Only API and confirm the port shown above."
confirm "PAPER is selected and Read-Only API is checked?" || refuse "gateway posture not confirmed"
run_packet_python -c "import ibapi" || refuse "official TWS API (ibapi) is not importable in .venv"

stage "Confirm the frozen campaign identity"
say "Interval: daily (1d), RTH trades, unadjusted bars."
say "Symbols: $SYMBOLS"
say "Cutoff: 2026-08-21 · duration: 9500 days · exchange: SMART"
say "Dataset: chronos-qqq-robustness-daily-v1"
say "Local packet root: $CAMPAIGN_ROOT"
warn "Changing any value requires a new reviewed campaign identity."
confirm "Use this exact frozen identity?" || refuse "campaign identity not approved"

stage "Capture the six daily histories"
if [[ -f "$CAPTURE_LOG" ]]; then
  note "Reusing $CAPTURE_LOG only after authenticating it against the manifest."
  run_packet_python "$PACKET_HELPER" validate-capture \
    --history-root "$HISTORY_ROOT" \
    --capture-log "$CAPTURE_LOG"
else
  say "The exporter is idempotent and refuses conflicting historical rows."
  capture_build=$(mktemp "$CAMPAIGN_ROOT/capture-build.XXXXXX")
  if ! run_packet_python -m chronos.histdata bars \
      --symbols "$SYMBOLS" \
      --end-date 2026-08-21 \
      --duration-days 9500 \
      --bar-size 1d \
      --history-root "$HISTORY_ROOT" \
      --exchange SMART | tee "$capture_build"; then
    refuse "capture failed; diagnostic output remains at $capture_build"
  fi
  mv "$capture_build" "$CAPTURE_LOG"
  run_packet_python "$PACKET_HELPER" validate-capture \
    --history-root "$HISTORY_ROOT" \
    --capture-log "$CAPTURE_LOG"
fi
note "No account identifier or credential is written to the capture log."

stage "Supply complete corporate-action streams"
say "Bars alone cannot produce the point-in-time total-return series required by QQQ v1."
say "Populate every JSON file in $ACTION_INPUT_ROOT with the complete split/dividend stream."
say "Use native ex-date values; never restate an old dividend to a later split basis."
for symbol in QQQ SPY IWM DIA GLD TLT; do
  [[ -f "$ACTION_INPUT_ROOT/$symbol.json" ]] || printf '[]\n' > "$ACTION_INPUT_ROOT/$symbol.json"
done
open_url "https://www.invesco.com/qqq-etf/en/home.html"
open_url "https://www.ssga.com/us/en/intermediary/etfs/spdr-sp-500-etf-trust-spy"
open_url "https://www.ssga.com/us/en/intermediary/etfs/spdr-dow-jones-industrial-average-etf-trust-dia"
open_url "https://www.ssga.com/us/en/intermediary/etfs/spdr-gold-shares-gld"
open_url "https://www.ishares.com/us/products/239710/ishares-russell-2000-etf"
open_url "https://www.ishares.com/us/products/239454/ishares-20-year-treasury-bond-etf"
note "Each item: {\"kind\":\"cash_dividend|split\",\"ex_date\":\"YYYY-MM-DD\",\"value\":number,\"source\":\"...\",\"note\":\"...\"}"
pause "Save all six complete files, then press Enter."
confirm "The streams came from official fund-sponsor records, not IBKR?" || refuse "independent primary action source not confirmed"
run_packet_python "$PACKET_HELPER" ingest-actions \
  --history-root "$HISTORY_ROOT" \
  --input-root "$ACTION_INPUT_ROOT"

stage "Record the independent 12-action sample"
say "Now cross-check at least 12 actions against a second source unrelated to IBKR and the sponsor streams."
open_url "https://www.nasdaq.com/market-activity/quotes/dividend-history"
step "Cover the full six-symbol panel; include split checks and GLD's no-distribution status."
step "Record discrepancies in the action files before continuing; do not wave them through."
confirm "At least 12 actions were independently reconciled with no unresolved conflict?" || refuse "attestation not complete"
seed_default ATTESTATION_SOURCE_ID "nasdaq-corporate-actions-independent-sample-2026-08-21"
seed_default ATTESTATION_COUNT "12"
ask ATTESTATION_SOURCE_ID "Exact independent source id used (recommended Nasdaq):"
ask ATTESTATION_COUNT "Number of independently sampled actions (minimum 12):"
[[ "$ATTESTATION_COUNT" =~ ^[0-9]+$ ]] || refuse "attestation count must be numeric"
(( ATTESTATION_COUNT >= 12 )) || refuse "attestation count must be at least 12"
[[ -n "$ATTESTATION_SOURCE_ID" ]] || refuse "attestation source id cannot be empty"
write_env ATTESTATION_SOURCE_ID "$ATTESTATION_SOURCE_ID"
write_env ATTESTATION_COUNT "$ATTESTATION_COUNT"
say "Attestation source id: $ATTESTATION_SOURCE_ID"

stage "Freeze the receipt and holdout declaration"
run_packet_python "$PACKET_HELPER" finalize-receipt \
  --history-root "$HISTORY_ROOT" \
  --capture-log "$CAPTURE_LOG" \
  --output "$SOURCE_RECEIPT"
say "Recommended partition map:"
say "  all symbols through 2024-01-10: seen"
say "  QQQ 2022-01-01 through 2024-01-10: explicitly burned"
say "  all symbols 2024-01-11 through 2026-08-21: clean final holdout"
confirm "Approve this map without using the clean partition for research?" || refuse "holdout map not approved"
run_packet_python "$PACKET_HELPER" build-declaration \
  --history-root "$HISTORY_ROOT" \
  --source-receipt "$SOURCE_RECEIPT" \
  --output "$DECLARATION" \
  --attestation-source-id "$ATTESTATION_SOURCE_ID" \
  --attestation-count "$ATTESTATION_COUNT"
note "Only classified_moves may be added after a genuine certification finding."

stage "Certify without tuning"
if ! run_packet_python "$REPO_ROOT/scripts/certify_dataset.py" certify \
    --declaration "$DECLARATION" \
    --history-root "$HISTORY_ROOT"; then
  warn "NOT_CERTIFIED is a valid result. Correct source evidence or classify a genuine event."
  refuse "certification failed; no release was frozen and no threshold may be changed"
fi

stage "Freeze and authenticate the release"
if [[ -e "$RELEASE_ROOT" ]]; then
  note "Release already exists; verifying it byte-for-byte instead of overwriting it."
else
  release_build=$(mktemp -d "$CAMPAIGN_ROOT/release-build.XXXXXX")
  if ! run_packet_python "$REPO_ROOT/scripts/certify_dataset.py" freeze \
      --declaration "$DECLARATION" \
      --history-root "$HISTORY_ROOT" \
      --output "$release_build"; then
    refuse "freeze failed; partial build retained at $release_build for inspection"
  fi
  mv "$release_build" "$RELEASE_ROOT"
fi
run_packet_python "$PACKET_HELPER" verify-release \
  --release-root "$RELEASE_ROOT" \
  --source-receipt "$SOURCE_RECEIPT" \
  --declaration "$DECLARATION"
note "Release: $RELEASE_ROOT"
note "Declaration: $DECLARATION"
note "Source receipt: $SOURCE_RECEIPT"

finish
